image: "mahieronymus/ad_sensitivity:2.0"

variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
 - Static Analysis Python
 - Static Analysis CPP
 - build
 - test

black:
  stage: Static Analysis Python
  script:
    - black --check scripts/
  allow_failure: false
  tags:
    - style

lint:
  stage: Static Analysis CPP
  script:
    - cpplint --linelength=120 --quiet --counting=toplevel --filter=-readability/fn_size,-legal/copyright,-runtime/references --recursive --exclude=src/scratch/*.cpp --exclude=build/* .
  tags:
    - style
  allow_failure: false

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=release -DTARGET=simulation  -DTRUSTED_DATA:BOOL=ON -DB_EIGHT:BOOL=ON && make -j4
  tags:
    - make

test:
  stage: test
  dependencies:
    - build
  script:
    - cd exe_scripts && bash docker_test.sh
  tags:
    - test