image: "python:3.7.6"

variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - python3 --version
  - pip3 install black
  - pip3 install cpplint

stages:
 - Static Analysis Python
 - Static Analysis CPP

black:
  stage: Static Analysis Python
  script:
    - black --check scripts/
  allow_failure: false

lint:
  stage: Static Analysis CPP
  script:
    - cpplint --linelength=120 --quiet --counting=toplevel --filter=-readability/fn_size,-legal/copyright,-runtime/references --recursive --exclude=src/scratch/*.cpp --exclude=build/* .
  allow_failure: false
