image: "python:3.7.6"

variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - python3 --version
  - pip3 install black

stages:
 - Static Analysis Python

black:
  stage: Static Analysis Python
  script:
    - black --check scripts/
  allow_failure: false