image: "mahieronymus/ad_sensitivity:2.12"

stages:
  - Static Analysis CPP
  - build


lint:
  stage: Static Analysis CPP
  script:
    - source /app/venv/bin/activate
    - cpplint --linelength=120 --quiet --counting=toplevel --filter=-build/include_subdir,-readability/fn_size,-legal/copyright,-runtime/references,-runtime/arrays,-build/c++11 --recursive --exclude=src/scratch/*.cpp --exclude=build/* .
  tags:
    - style
  allow_failure: false

build:
  stage: build
  artifacts:
    untracked: true
  script:
    - mkdir build
    - cd build && 
      cmake .. -DCMAKE_BUILD_TYPE=release -DTARGET=simulation -DTRUSTED_DATA:BOOL=ON -DB_EIGHT:BOOL=ON -DCCN_AKM:BOOL=ON && 
      make -j4
    - cd .. && mkdir build_interface
    - cd build_interface && 
      cmake .. -DCMAKE_BUILD_TYPE=release -DTARGET=python_interface  -DTRUSTED_DATA:BOOL=ON -DB_EIGHT:BOOL=ON -DCCN_AKM:BOOL=ON && 
      make -j4
    - cd .. && mkdir build_regrid
    - cd build_regrid &&
      cmake .. -DCMAKE_BUILD_TYPE=release -DTARGET=regrid -DCOMPRESSION_LEVEL=6 -DTRUSTED_DATA:BOOL=ON -DB_EIGHT:BOOL=ON -DCCN_AKM:BOOL=ON &&
      make -j4
    - cd .. && mkdir build_loom
    - cd build_loom &&
      cmake .. -DCMAKE_BUILD_TYPE=release -DTARGET=loom -DCOMPRESS_OUTPUT:BOOL=ON -DCOMPRESSION_LEVEL=6 -DTRUSTED_DATA:BOOL=ON -DB_EIGHT:BOOL=ON -DCCN_AKM:BOOL=ON &&
      make -j4
  tags:
    - make
  allow_failure: false
