#!/bin/bash
#SBATCH --job-name=t_wcb_traject_flagged
#SBATCH --output=logs/test_wcb_traject_flagged_%A.out
#SBATCH --error=logs/test_wcb_traject_flagged_%A.err
#SBATCH --time=0:10:00
#SBATCH -p parallel
#SBATCH --nodes=2
#SBATCH --ntasks=64
#SBATCH -A m2_zdvresearch
#SBATCH --mem-per-cpu=4000
#SBATCH -C skylake

# module load data/netCDF-C++4/4.3.1-gompi-2019a
# module load devel/Boost/1.70.0-gompi-2019a-Python-2.7.16
# module load numlib/GSL/2.5-GCCcore-8.3.0


# pdsh -w $SLURM_JOB_NODELIST 
module load tools/parallel/20181122
module load numlib/GSL/2.5-GCCcore-6.4.0
module load data/netCDF-C++4/4.3.0-foss-2018a
module load devel/Boost/1.68.0-foss-2018a
# pdsh -w $SLURM_JOB_NODELIST echo $LD_LIBRARY_PATH 

load_command="module load tools/parallel/20181122 && module load numlib/GSL/2.5-GCCcore-6.4.0 && module load data/netCDF-C++4/4.3.0-foss-2018a && module load devel/Boost/1.68.0-foss-2018a"

# Environmental conditions
SCALING_FACTOR="1.0"
AUTO_TYPE="3"
# General stuff
INPUT_FILENAME="/lustre/project/m2_jgu-tapt/cosmo_output/vladiana/traj/traj_t000000_p002.nc_wcb"
TIMESTEP="0.01"
SNAPSHOT_INDEX="250"
START_OVER="1"
FIXED_ITERATION="0"
# Max: 52.205 hours = 187940 seconds for the input above with 20161 timesteps.
# But 187940 seconds is the last time where for traj==0 we get non NaNs
TARGET_TIME="187940.0"
WRITE_INDEX="5000"
# Number of tasks per node
NODE_TASKS="32"
scontrol show hostnames > /tmp/list_of_nodes
# scontrol show hostnames
echo ${SLURM_JOB_NODELIST}
# Create directories on all nodes
pdsh -w $SLURM_JOB_NODELIST mkdir -p /tmp/build/apps/src/microphysics/
# sbcast dmin_wetgrowth_lookup.dat /tmp/dmin_wetgrowth_lookup.dat
# sbcast build/apps/src/microphysics/trajectories /tmp/apps/src/microphysics/trajectories
# ls /tmp/
# ls
pdsh -w $SLURM_JOB_NODELIST cp /home/mahieron/process_plot_scripts/dmin_wetgrowth_lookup.dat /tmp/dmin_wetgrowth_lookup.dat
pdsh -w $SLURM_JOB_NODELIST cp /home/mahieron/process_plot_scripts/build/apps/src/microphysics/trajectories /tmp/build/apps/src/microphysics/trajectories
pdsh -w $SLURM_JOB_NODELIST cd /tmp

# Define env_parallel
. $(which env_parallel.bash)


# parameterize parallel
my_parallel="env_parallel --workdir /tmp --sshloginfile /tmp/list_of_nodes -j $NODE_TASKS --no-notice --delay .2"
# see https://rcc.uchicago.edu/docs/tutorials/kicp-tutorials/running-jobs.html
# parameterize srun as in https://mogonwiki.zdv.uni-mainz.de/dokuwiki/node_local_scheduling
my_srun="srun -n1 -N1 --exclusive --cpu-bind=cores"

# TARGET_TIME="403220"
# INPUT_FILENAME="/lustre/project/m2_zdvresearch/mahieron/traj_appended/traj_t000000_p001.nc_wcb"
# $my_parallel "$my_srun build/apps/src/microphysics/./trajectories -w ${WRITE_INDEX} -a ${AUTO_TYPE} -t ${FIXED_ITERATION} -s ${START_OVER} -f ${TARGET_TIME} -d ${TIMESTEP} -i ${SNAPSHOT_INDEX} -b ${SCALING_FACTOR} -o /lustre/project/m2_zdvresearch/mahieron/wcb_conv_slan/wcb${TARGET_TIME}_traj{}_MAP_t001680_p002 -l ${INPUT_FILENAME} -r {}" ::: {0..350} &


TARGET_TIME="324020"
INPUT_FILENAME="/lustre/project/m2_jgu-tapt/cosmo_output/vladiana/traj/traj_t001320_p002.nc_wcb"
$my_parallel "$my_srun /tmp/build/apps/src/microphysics/./trajectories -w ${WRITE_INDEX} -a ${AUTO_TYPE} -t ${FIXED_ITERATION} -s ${START_OVER} -f ${TARGET_TIME} -d ${TIMESTEP} -i ${SNAPSHOT_INDEX} -b ${SCALING_FACTOR} -o /lustre/project/m2_zdvresearch/mahieron/wcb_conv_slan_test/wcb${TARGET_TIME}_traj{}_MAP_t001320_p002 -l ${INPUT_FILENAME} -r {}" ::: {0..120} &
wait

