#!/bin/bash
#SBATCH --job-name=plot2
#SBATCH --output=logs/plot2_%A_%a.out
#SBATCH --error=logs/plot2_%A_%a.err
#SBATCH --time=24:00:00
#SBATCH -p parallel
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH -A m2_zdvresearch
#SBATCH --mem=220G
#SBATCH -C broadwell

module load tools/parallel/20170622
module load lang/Python/3.7.4-GCCcore-8.3.0
source ../plot_env/bin/activate

INPUT_FILENAME="/lustre/project/m2_zdvresearch/mahieron/wcb_traj_flag_deriv_mult_min2/tmp_concat"
OUTPUT_PATH="/lustre/project/m2_zdvresearch/mahieron/wcb_traj_flag_deriv_mult_min2/pics/"
my_srun="srun -n1 -N1 --exclusive --cpu-bind=cores --mem-per-cpu=22G"
my_parallel="parallel -j 10 --no-notice --joblog logs/%A_runtask.log"
KEYS=(Misc Hail)
OUT_PARAMS=(p S qc qr qv)

# There are 10 combinations
$my_parallel "$my_srun python plot_mogon.py ${INPUT_FILENAME} {1} {2} ${OUTPUT_PATH}" ::: ${KEYS[@]} ::: ${OUT_PARAMS[@]}

# $my_srun python plot_mogon.py ${INPUT_FILENAME} Misc p ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Misc S ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Misc qc ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Misc qr ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Misc qv ${OUTPUT_PATH} &

# $my_srun python plot_mogon.py ${INPUT_FILENAME} Hail p ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Hail S ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Hail qc ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Hail qr ${OUTPUT_PATH} &
# $my_srun python plot_mogon.py ${INPUT_FILENAME} Hail qv ${OUTPUT_PATH} &
# wait