#!/bin/bash
#SBATCH --job-name=wcb_merge
#SBATCH --output=logs/wcb_merge_%A.out
#SBATCH --error=logs/wcb_merge_%A.err
#SBATCH --time=10:00:00
#SBATCH -p parallel
#SBATCH --ntasks=1
#SBATCH -A m2_zdvresearch
#SBATCH --mem=64GB # Default value
#SBATCH -C skylake

module purge
module load lang/Python/3.7.4-GCCcore-8.3.0
source  /home/mahieron/plot_env/bin/activate
echo "Merging output from ${1} to ${2}"
# arg 1 is source ie
# /lustre/project/m2_zdvresearch/mahieron/perturbed_ensembles/config_ens_least/
# or /lustre/project/m2_zdvresearch/mahieron/perturbed_ensembles/config_ens_separate/
# arg 2 is destination ie
# /lustre/project/m2_zdvresearch/mahieron/perturbed_ensembles/config_ens_least.nc_wcb
# or /lustre/project/m2_zdvresearch/mahieron/perturbed_ensembles/config_ens_separate.nc_wcb
python ../scripts/merge.py ${1} ${2}
