#!/bin/bash
#SBATCH --job-name=pred_ens
#SBATCH --output=logs/%x_%A.out
#SBATCH --error=logs/%x_%A.err
#SBATCH --time=24:00:00
#SBATCH -p parallel
#SBATCH --ntasks=1
#SBATCH -A m2_zdvresearch
#SBATCH --mem=62GB
#SBATCH -C skylake

module purge
module load lang/Python/3.7.4-GCCcore-8.3.0
source  /home/mahieron/plot_env/bin/activate

cd ..
SAVEDPWD=$(pwd)
export AD_SIM_HOME=/localscratch/${SLURM_JOB_ID}
# "/lustre/project/m2_zdvresearch/mahieron/perturbed_ensembles/yadda"
DATA_PATH=$1
SAVE_OUTPUTPATH="/lustre/project/m2_zdvresearch/mahieron/predictions/"
OUTPUT_PATH="${AD_SIM_HOME}/output/"
MODEL_PATH="${AD_SIM_HOME}/model/"
SCRIPTS_PATH="${AD_SIM_HOME}/scripts/"

copy_out(){
    echo "Copy from ${OUTPUT_PATH}*.nc to ${SAVE_OUTPUTPATH}*.nc"
    find ${OUTPUT_PATH} -type f -name "*.nc" -exec cp {} ${SAVE_OUTPUTPATH} \;
    wait
    exit 0
}

if [ ! -d "${SAVE_OUTPUTPATH}" ]
then
    mkdir -p "${SAVE_OUTPUTPATH}"
fi

if [ ! -d "${OUTPUT_PATH}" ]
then
    mkdir -p "${OUTPUT_PATH}"
fi

if [ ! -d "${MODEL_PATH}" ]
then
    mkdir -p "${MODEL_PATH}"
fi

if [ ! -d "${SCRIPTS_PATH}" ]
then
    mkdir -p "${SCRIPTS_PATH}"
fi

# copy scripts
cp scripts/*.py ${SCRIPTS_PATH}
# copy models
cp data/models/subset_tran_strat_* ${MODEL_PATH}

SUFF=${DATA_PATH##*/}
SUFF=${SUFF%.*}
OUTPUT_FILE=${OUTPUT_PATH}matrix_thresh20_${SUFF}.nc

cd ${AD_SIM_HOME}
python ${AD_SIM_HOME}/scripts/segment_identifier.py \
--verbosity 3 \
--min_threshold=-20 \
--n_trajs=40 \
--load_models ${MODEL_PATH}subset_tran_strat_ \
--data_path ${DATA_PATH} \
--store_name ${OUTPUT_FILE}

copy_out
