#ifndef INCLUDE_MISC_CONSTANTS_SIM_READER_H_
#define INCLUDE_MISC_CONSTANTS_SIM_READER_H_

#include <array>
#include <string>
#include <vector>

#define DELTA_TIMESTEP 30
/**
 * Define the compression level. Level 9 is the best compression but level 6
 * is much faster and uses something between 2 and 5 times as much space.
 */
#define COMPRESSION_LEVEL 6

const std::array<std::string, 29> order_sens = {
        "db_ccn_1", "db_ccn_2", "db_ccn_3", "db_v",
        "dc_ccn_1", "dc_ccn_2", "dc_ccn_3", "dg_ccn_1",
        "dgraupel_a_geo", "dgraupel_b_geo", "dgraupel_b_vel", "dh_ccn_1",
        "dhande_ccn_fac", "di_ccn_1", "dice_a_geo", "dice_b_geo",
        "dice_b_vel", "dkin_visc_air", "dp_sat_melt", "drain_a_geo",
        "drain_a_vel", "drain_alpha", "drain_b_geo", "drain_b_vel",
        "drain_beta", "drain_cmu3", "drain_mu", "drain_nu",
        "dsnow_b_geo"
};

const std::array<std::string, 169> loom_order_sens = {
        "dC_mult", "dD_conv_i", "dD_conv_ig", "dD_conv_sg",
        "dD_crit_i", "dD_crit_r", "dD_rainfrz_gh", "dD_rainfrz_ig",
        "dT_mult_max", "dT_mult_min", "dT_nuc", "da_HET",
        "da_prime", "da_v", "dalpha_depo", "db_HET",
        "db_ccn_1", "db_ccn_2", "db_ccn_3", "db_prime",
        "db_v", "dc_ccn_1", "dc_ccn_2", "dc_ccn_3",
        "dc_prime", "dcloud_a_geo", "dcloud_a_vel", "dcloud_b_geo",
        "dcloud_b_vel", "dcloud_d_crit_c", "dcloud_max_x", "dcloud_min_x",
        "dcloud_min_x_act", "dcloud_min_x_conversion", "dcloud_min_x_freezing", "dcloud_min_x_riming",
        "dcloud_q_crit_c", "ddv0", "decoll_gg", "decoll_gg_wet",
        "decoll_min", "dg_ccn_1", "dg_ccn_2", "dg_ccn_3",
        "dgraupel_a_geo", "dgraupel_a_vel", "dgraupel_a_ven", "dgraupel_b_geo",
        "dgraupel_b_vel", "dgraupel_d_crit_c", "dgraupel_max_x", "dgraupel_min_x",
        "dgraupel_min_x_collection", "dgraupel_min_x_conversion", "dgraupel_min_x_depo", "dgraupel_min_x_evap",
        "dgraupel_min_x_melt", "dgraupel_min_x_riming", "dgraupel_min_x_sedimentation", "dgraupel_mu",
        "dgraupel_q_crit_c", "dgraupel_s_vel", "dgraupel_vsedi_max", "dgraupel_vsedi_min",
        "dh_ccn_1", "dh_ccn_2", "dhail_a_geo", "dhail_a_vel",
        "dhail_a_ven", "dhail_b_geo", "dhail_b_vel", "dhail_d_crit_c",
        "dhail_max_x", "dhail_min_x", "dhail_min_x_depo", "dhail_min_x_melt",
        "dhail_min_x_riming", "dhail_min_x_sedimentation", "dhail_q_crit_c", "dhail_s_vel",
        "dhail_vsedi_max", "dhail_vsedi_min", "dhande_ccn_fac", "di_ccn_1",
        "di_ccn_2", "dice_a_geo", "dice_a_vel", "dice_a_ven",
        "dice_b_geo", "dice_b_vel", "dice_d_crit_c", "dice_max_x",
        "dice_min_x", "dice_min_x_act", "dice_min_x_collection", "dice_min_x_collision",
        "dice_min_x_conversion", "dice_min_x_depo", "dice_min_x_evap", "dice_min_x_melt",
        "dice_min_x_nuc_hetero", "dice_min_x_nuc_homo", "dice_min_x_riming", "dice_min_x_sedimentation",
        "dice_q_crit_c", "dice_s_vel", "dice_vsedi_max", "dice_vsedi_min",
        "dk_1_accr", "dk_1_conv", "dk_2_conv", "dk_b",
        "dk_r", "dkc_autocon", "dkin_visc_air", "dna_dust",
        "dna_orga", "dna_soot", "dni_het_max", "dni_hom_max",
        "dp_ccn", "dp_sat_melt", "dq_crit_fr", "dq_crit_i",
        "dq_crit_r", "dr_0", "drain_a_geo", "drain_a_vel",
        "drain_alpha", "drain_b_geo", "drain_b_vel", "drain_beta",
        "drain_cmu0", "drain_cmu1", "drain_cmu2", "drain_cmu3",
        "drain_cmu4", "drain_cmu5", "drain_gamma", "drain_max_x",
        "drain_min_x", "drain_min_x_collection", "drain_min_x_evap", "drain_min_x_freezing",
        "drain_min_x_riming", "drain_min_x_sedimentation", "drain_mu", "drain_nu",
        "drho_vel", "drho_vel_c", "dsnow_a_geo", "dsnow_a_vel",
        "dsnow_a_ven", "dsnow_b_geo", "dsnow_b_vel", "dsnow_d_crit_c",
        "dsnow_max_x", "dsnow_min_x", "dsnow_min_x_collection", "dsnow_min_x_depo",
        "dsnow_min_x_evap", "dsnow_min_x_melt", "dsnow_min_x_riming", "dsnow_min_x_sedimentation",
        "dsnow_q_crit_c", "dsnow_s_vel", "dsnow_vsedi_max", "dsnow_vsedi_min", "dx_conv"
};

const std::array<std::string, 26> order_par = {
        "pressure",
        "T",
        "w",
        "S",
        "QC",
        "QR",
        "QV",
        "NCCLOUD",
        "NCRAIN",
        "QI",
        "NCICE",
        "QS",
        "NCSNOW",
        "QG",
        "NCGRAUPEL",
        "QH",
        "NCHAIL",
        "latent_heat",
        "latent_cool",
        "lat",
        "lon",
        "relative_lat",
        "relative_lon",
        "time_after_ascent",
        "asc600",
        "phase"
};

const std::array<std::string, 2> order_misc = {
        "Top_Parameter",
        "counts"
};

enum Par_idx {
    pressure,
    temperature,
    ascent,
    saturation,
    qc,
    qr,
    qv,
    nc,
    nr,
    qi,
    ni,
    qs,
    ns,
    qg,
    ng,
    qh,
    nh,
    heat,
    cool,
    lat,
    lon,
    rel_lat,
    rel_lon,
    time_after_ascent,
    asc600,
    phase,
    n_pars
};

enum Misc_idx {
    ranking,
    counts,
    n_misc
};

enum Sens_par_idx {
    db_ccn_1,
    db_ccn_2,
    db_ccn_3,
    db_v,
    dc_ccn_1,
    dc_ccn_2,
    dc_ccn_3,
    dg_ccn_1,
    dgraupel_a_geo,
    dgraupel_b_geo,
    dgraupel_b_vel,
    dh_ccn_1,
    dhande_ccn_fac,
    di_ccn_1,
    dice_a_geo,
    dice_b_geo,
    dice_b_vel,
    dkin_visc_air,
    dp_sat_melt,
    drain_a_geo,
    drain_a_vel,
    drain_alpha,
    drain_b_geo,
    drain_b_vel,
    drain_beta,
    drain_cmu3,
    drain_mu,
    drain_nu,
    dsnow_b_geo,
    n_sens_pars
};

enum Sens_loompar_idx {
    dC_mult,
    dD_conv_i,
    dD_conv_ig,
    dD_conv_sg,
    dD_crit_i,
    dD_crit_r,
    dD_rainfrz_gh,
    dD_rainfrz_ig,
    dT_mult_max,
    dT_mult_min,
    dT_nuc,
    da_HET,
    da_prime,
    da_v,
    dalpha_depo,
    db_HET,
    db_ccn_1_loom,
    db_ccn_2_loom,
    db_ccn_3_loom,
    db_prime,
    db_v_loom,
    dc_ccn_1_loom,
    dc_ccn_2_loom,
    dc_ccn_3_loom,
    dc_prime,
    dcloud_a_geo,
    dcloud_a_vel,
    dcloud_b_geo,
    dcloud_b_vel,
    dcloud_d_crit_c,
    dcloud_max_x,
    dcloud_min_x,
    dcloud_min_x_act,
    dcloud_min_x_conversion,
    dcloud_min_x_freezing,
    dcloud_min_x_riming,
    dcloud_q_crit_c,
    ddv0,
    decoll_gg,
    decoll_gg_wet,
    decoll_min,
    dg_ccn_1_loom,
    dg_ccn_2,
    dg_ccn_3,
    dgraupel_a_geo_loom,
    dgraupel_a_vel,
    dgraupel_a_ven,
    dgraupel_b_geo_loom,
    dgraupel_b_vel_loom,
    dgraupel_d_crit_c,
    dgraupel_max_x,
    dgraupel_min_x,
    dgraupel_min_x_collection,
    dgraupel_min_x_conversion,
    dgraupel_min_x_depo,
    dgraupel_min_x_evap,
    dgraupel_min_x_melt,
    dgraupel_min_x_riming,
    dgraupel_min_x_sedimentation,
    dgraupel_mu,
    dgraupel_q_crit_c,
    dgraupel_s_vel,
    dgraupel_vsedi_max,
    dgraupel_vsedi_min,
    dh_ccn_1_loom,
    dh_ccn_2,
    dhail_a_geo,
    dhail_a_vel,
    dhail_a_ven,
    dhail_b_geo,
    dhail_b_vel,
    dhail_d_crit_c,
    dhail_max_x,
    dhail_min_x,
    dhail_min_x_depo,
    dhail_min_x_melt,
    dhail_min_x_riming,
    dhail_min_x_sedimentation,
    dhail_q_crit_c,
    dhail_s_vel,
    dhail_vsedi_max,
    dhail_vsedi_min,
    dhande_ccn_fac_loom,
    di_ccn_1_loom,
    di_ccn_2,
    dice_a_geo_loom,
    dice_a_vel,
    dice_a_ven,
    dice_b_geo_loom,
    dice_b_vel_loom,
    dice_d_crit_c,
    dice_max_x,
    dice_min_x,
    dice_min_x_act,
    dice_min_x_collection,
    dice_min_x_collision,
    dice_min_x_conversion,
    dice_min_x_depo,
    dice_min_x_evap,
    dice_min_x_melt,
    dice_min_x_nuc_hetero,
    dice_min_x_nuc_homo,
    dice_min_x_riming,
    dice_min_x_sedimentation,
    dice_q_crit_c,
    dice_s_vel,
    dice_vsedi_max,
    dice_vsedi_min,
    dk_1_accr,
    dk_1_conv,
    dk_2_conv,
    dk_b,
    dk_r,
    dkc_autocon,
    dkin_visc_air_loom,
    dna_dust,
    dna_orga,
    dna_soot,
    dni_het_max,
    dni_hom_max,
    dp_ccn,
    dp_sat_melt_loom,
    dq_crit_fr,
    dq_crit_i,
    dq_crit_r,
    dr_0,
    drain_a_geo_loom,
    drain_a_vel_loom,
    drain_alpha_loom,
    drain_b_geo_loom,
    drain_b_vel_loom,
    drain_beta_loom,
    drain_cmu0,
    drain_cmu1,
    drain_cmu2,
    drain_cmu3_loom,
    drain_cmu4,
    drain_cmu5,
    drain_gamma,
    drain_max_x,
    drain_min_x,
    drain_min_x_collection,
    drain_min_x_evap,
    drain_min_x_freezing,
    drain_min_x_riming,
    drain_min_x_sedimentation,
    drain_mu_loom,
    drain_nu_loom,
    drho_vel,
    drho_vel_c,
    dsnow_a_geo,
    dsnow_a_vel,
    dsnow_a_ven,
    dsnow_b_geo_loom,
    dsnow_b_vel,
    dsnow_d_crit_c,
    dsnow_max_x,
    dsnow_min_x,
    dsnow_min_x_collection,
    dsnow_min_x_depo,
    dsnow_min_x_evap,
    dsnow_min_x_melt,
    dsnow_min_x_riming,
    dsnow_min_x_sedimentation,
    dsnow_q_crit_c,
    dsnow_s_vel,
    dsnow_vsedi_max,
    dsnow_vsedi_min,
    dx_conv,
    n_sens_loompar
};

enum Dim_idx {
    time_dim_idx,
    trajectory_dim_idx,
    ensemble_dim_idx,
    output_para_idx,
    n_dims
};

enum Grid_dim_idx {
    outp_dim_idx,
    time_griddim_idx,
    p_dim_idx,
    lat_dim_idx,
    lon_dim_idx,
    n_griddims
};

enum Loom_dim_idx {
    outp_loomdim_idx,
    phase_loomdim_idx,
    time_loomdim_idx,
    n_loomdims
};


#endif  // INCLUDE_MISC_CONSTANTS_SIM_READER_H_
